name: PytorchLightningEnv
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python
  - pip
  - cudatoolkit=10.2
  - pytorch::pytorch
  - pytorch::torchvision
  - conda-forge::pytorch-lightning=1.2.10
  - tensorboard
  # - pathlib2
  - seaborn
  - numpy
  - pandas
  - autopep8
  - flake8
  - jupyter
  - pip:
      # - pytorch-lightning-bolts
      - test-tube
prefix: ~/anaconda3/envs/PytorchEnv
